# Generated by Django 4.2.4 on 2023-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50)),
                ('encrypted_password', models.CharField(max_length=50)),
                ('npsso_token', models.CharField(max_length=64)),
            ],
        ),
    ]
